[global]
workgroup = VULNBOX
server string = VulnBox File Server
security = user
map to guest = Bad User
smb ports = 445

[public]
path = /srv/samba/public
browseable = yes
writable = yes
guest ok = yes
read only = no

[backups]
path = /srv/samba/backups
browseable = yes
writable = yes
guest ok = yes
read only = no
