/**
 * Shared Zod schemas — pagination, ID params, and other reusable primitives.
 */

import { z } from 'zod';

// ── Pagination ───────────────────────────────────────────────────────────────

export const PaginationSchema = z.object({
  limit: z.coerce
    .number()
    .int('limit must be an integer')
    .positive('limit must be positive')
    .max(500, 'limit cannot exceed 500')
    .default(50),
  offset: z.coerce
    .number()
    .int('offset must be an integer')
    .min(0, 'offset must be non-negative')
    .default(0),
});

export type Pagination = z.infer<typeof PaginationSchema>;

// ── ID params ────────────────────────────────────────────────────────────────

/**
 * Cuid2 IDs — 24-char alphanumeric strings generated by Prisma @default(cuid()).
 * We accept any non-empty string here since cuid format is internal.
 */
export const IdParamSchema = z.object({
  id: z.string().min(1, 'id is required'),
});

export const ScanIdParamSchema = z.object({
  scanId: z.string().min(1, 'scanId is required'),
});

export const TargetIdParamSchema = z.object({
  targetId: z.string().min(1, 'targetId is required'),
});

// ── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Target string — accepts bare IPs, hostnames, host:port, or full URLs.
 * Does NOT assume or prepend any protocol. Targets are stored exactly as given.
 */
export const TargetStringSchema = z
  .string()
  .min(1, 'target is required')
  .transform((val) => val.trim());

/** @deprecated Use TargetStringSchema — kept for backward compat */
export const UrlStringSchema = TargetStringSchema;

/**
 * IPv4 address — loose pattern that catches obvious non-IPs without being
 * pedantic about range validation.
 */
export const Ipv4Schema = z
  .string()
  .regex(/^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$/, 'must be a valid IPv4 address');

/**
 * Port number, 1-65535.
 */
export const PortSchema = z.number().int().min(1).max(65535);
