/**
 * Shared Zod schemas — pagination, ID params, and other reusable primitives.
 */

import { z } from 'zod';

// ── Pagination ───────────────────────────────────────────────────────────────

export const PaginationSchema = z.object({
  limit: z.coerce
    .number()
    .int('limit must be an integer')
    .positive('limit must be positive')
    .max(500, 'limit cannot exceed 500')
    .default(50),
  offset: z.coerce
    .number()
    .int('offset must be an integer')
    .min(0, 'offset must be non-negative')
    .default(0),
});

export type Pagination = z.infer<typeof PaginationSchema>;

// ── ID params ────────────────────────────────────────────────────────────────

/**
 * Cuid2 IDs — 24-char alphanumeric strings generated by Prisma @default(cuid()).
 * We accept any non-empty string here since cuid format is internal.
 */
export const IdParamSchema = z.object({
  id: z.string().min(1, 'id is required'),
});

export const ScanIdParamSchema = z.object({
  scanId: z.string().min(1, 'scanId is required'),
});

export const TargetIdParamSchema = z.object({
  targetId: z.string().min(1, 'targetId is required'),
});

// ── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Coerce a string that may or may not carry an http/https prefix into a valid
 * URL string. We normalize at the schema level so route handlers never need to
 * repeat that logic.
 */
export const UrlStringSchema = z
  .string()
  .min(1, 'url is required')
  .transform((val) => (val.startsWith('http') ? val : `https://${val}`))
  .pipe(z.string().url('must be a valid URL'));

/**
 * IPv4 address — loose pattern that catches obvious non-IPs without being
 * pedantic about range validation.
 */
export const Ipv4Schema = z
  .string()
  .regex(/^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$/, 'must be a valid IPv4 address');

/**
 * Port number, 1-65535.
 */
export const PortSchema = z.number().int().min(1).max(65535);
